# Generated by Django 3.2.7 on 2023-10-17 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+41524240242', max_length=30, region=None, verbose_name='Phone Number')),
                ('bio', models.TextField(default='say something about yourself', verbose_name='Bio')),
                ('profile_photo', models.ImageField(default='/profile_default.png', upload_to='', verbose_name='Profile Photo')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Gender')),
                ('website', models.URLField()),
                ('country', django_countries.fields.CountryField(default='US', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='New York', max_length=180, verbose_name='City')),
                ('num_following', models.IntegerField(blank=True, default=0, null=True, verbose_name='Following')),
                ('num_followers', models.IntegerField(blank=True, default=0, null=True, verbose_name='Followers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
